### ISSUE TITLE
Any word on when this will be in IE/Edge?

### ISSUE THREAD

**Issue by StoneCypher** [MicrosoftEdge/Gamepad-Sample#3]
Neither IE nor edge run this code yet.

This code is more than two years old.

**Comment by StoneCypher** [comment]
oh, i see

it turns out that the actual problem is that the edge implementation of html5 controllers won't work except with microsoft joysticks

meaning html5 games in your html5 app platform still aren't viable even though it's now been almost four years since you launched store (feb 29 2012)

this and no subscription payments are really killing the viability of your store for gaming

**Comment by teddink** [comment]
We hear your feedback loud and clear and I can assure you that this is on our backlog of work that we would like to complete, but do not have an ETA that we can share.

**Comment by StoneCypher** [comment]
this has been the #1 community request since IE5.5 was the first IE version to gather request statistics, and is a primary blocker on the development community's ability to proceed with this as one of the four primary platforms microsoft publically claimed in 2012

it's been 15 years

it would take less than a week of work to get this right

given the inflow of capital from allowing game development, it would make easy economic sense to outsource this, since you haven't found time for it in 17 years so far

there's a point at which i have to wonder about your team's priorities, @teddink.  you've got people working on ambient light in the room, because apparently visible brightness is a more important input method than actual input methods.  you're implementing fido2, something nobody will ever use.  you're implementing webkitdirectory and webkitrelative path.  

you're implementing vp9 and webm, a tremendous amount of work which is not only unimportant, but which google will pull out from under you the second you're done, just like they always do, because you're charlie brown and you just don't learn about lucy and the football.

but joysticks?

nah, let's just wait another 17 years.  the web and your html developers don't need games.  games are dumb.

let's get ambient light working.  that's more important.

clearly it's about your backlog, even though you're implementing things whose standards didn't show up until 16 years after you were more than a public year into neglecting 300 lines of code that would massively impact the platform that says developers but doesn't do it.

not your priorities.

**Comment by StoneCypher** [comment]
this has been the #1 community request since IE5.5 was the first IE version to gather request statistics, and is a primary blocker on the development community's ability to proceed with this as one of the four primary platforms microsoft publically claimed in 2012

it's been 17 years.  it's 2016 and you started showing this as the #1 request in the end of 1999.

it would take less than a week of work to get this right.  the hard part is already done in the platform api.  all you're doing is exposing signatures.  this isn't work or backlog; this is lack of caring what your dependents need, but successfully caring about appearing to care.

given the inflow of capital from allowing game development, it would make easy economic sense to outsource this, since you haven't found time for it in 17 years so far

you've got people working on ambient light in the room, as an input method.  you're implementing fido2.  you're implementing webkitdirectory and webkitrelative path.  you're implementing vp9 and webm.

all of these things are much more work than joysticks, with much less impact, all of which have come up in the last five years.

seventeen years you've been keeping game developers waiting with no other options.

it's not that you don't have time.  it's about what you're prioritizing.

if you have time to invent ambient light as an input method, you have time to expose the APIs that other developers already wrote.  export bridges to the javascript virtual machine are not difficult or complicated.

i'd like to recommend that when you tell other developers you don't have time, you remember that those developers know how much time it would actually take, and know where to check what you're spending your time on, @teddink .

**Comment by jacobrossi** [comment]
Thanks for the feedback @StoneCypher.  This issue tracker is not the correct place for requesting features or improvements in the browser. It is for issues with the sample code we've released. 

Please see our [UserVoice](http://uservoice.microsoftedge.com) where you can submit and vote on improvements to our platform. It does not appear anyone in the community has made your request yet on our UserVoice, so feel free to submit the idea and vote it up!
